<!doctype html>
<html lang="fr" >

	<head>

		<meta charset="utf-8">

		<?php echo $this->headMeta() ?>
		<?php echo $this->headTitle() ?>
		<?php echo $this->headLink() ?>
		<?php echo $this->headStyle() ?>
		<?php echo $this->headScript() ?>

		<script src="/js/libs/modernizr-2.5.3.min.js"></script>
		
	</head>
	
	<body>

		<?php echo $this->layout()->content ?>
	
		<?php echo $this->inlineScript() ?>
	
	</body>
	
</html>